# Generated by Django 4.2.27 on 2025-12-09 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sala')),
                ('capacidade', models.PositiveIntegerField(default=1, verbose_name='Capacidade Máxima')),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização/Prédio')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Em Uso/Disponível')),
            ],
            options={
                'verbose_name': 'Sala de Reunião',
                'verbose_name_plural': 'Salas de Reunião',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início da Reserva')),
                ('data_fim', models.DateTimeField(verbose_name='Fim da Reserva')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('objetivo', models.TextField(verbose_name='Objetivo da Reunião')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_reservas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário/Usuário')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_sala', to='reservas.sala')),
            ],
            options={
                'verbose_name': 'Reserva de Sala',
                'verbose_name_plural': 'Reservas de Salas',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Recurso')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('salas', models.ManyToManyField(related_name='recursos', to='reservas.sala', verbose_name='Salas com este Recurso')),
            ],
            options={
                'verbose_name': 'Recurso da Sala',
                'verbose_name_plural': 'Recursos das Salas',
            },
        ),
    ]
